version: "3.8"

services:
  frontend:
    build: ./student-frontend
    container_name: react_app
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./student-app
    container_name: Laravel
    env_file:
      - ./student-app/.env
    ports:
      - "8000:8000"
    volumes:
      - ./student-app/.env:/var/www/.env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: student_app
      MYSQL_USER: root
      MYSQL_PASSWORD: Sumo@3396
      MYSQL_ROOT_PASSWORD: Sumo@3396
    volumes:
      - ./mysql/data:/var/lib/mysql
